### ISSUE TITLE
std::bad_alloc error

### ISSUE THREAD

**Issue by youngjae41** [sudarshan-s-harithas/CCO-VOXEL#2]
Hello!

Thank you for sharing the good code

![Screenshot from 2022-06-27 17-35-41](https://user-images.githubusercontent.com/55374072/175898383-7649adc0-4ab0-4633-9312-a9de378cf526.png)
'

Error occurs during test

I think Controller.cpp problem

not change offboard mode 

I used master Firmware version

**Comment by sudarshan-s-harithas** [comment]
Hi,

Can you please give a few more details? 
I hope that the weights parameter has been updated in the CCO_VOXEL_Planner.launch file.
And did this error occur in the middle of the run or as soon as you start the controller. 

If the controller is the issue can you try  to publish a dummy trajectory to the controller and check its response? 
Also, let me know the PX4 and mavros version at your end so that I can attempt to replicate the issue. 

Thank You

**Comment by youngjae41** [comment]
thanks for the reply

I used the PX4 master firmware that I downloaded yesterday.

The Rosrun CCO_VOXEL controller does not convert to OFFboard mode.

press 2D nav goal, the above error occurs.

Install mavros is sudo apt-get I installed it using ros-noetic-mavros.

**Comment by sudarshan-s-harithas** [comment]
A few debugging suggestions 

1. Ensure you have set the correct path to the weights file in CCO_VOXEL_Planner.launch, this seems to be a memory allocation error
2.  Use the offboard example given [here](https://docs.px4.io/v1.12/en/ros/mavros_offboard.html), to check if the offboard control works fine on your system. 
3.  The controller shifts to offboard once the trajectory is published, it is possible that there is no trajectory in the topic and therefore the controller has not shifted to offboard mode.

Please try these suggestions. 

Thank You

**Comment by youngjae41** [comment]
Hello

I use catkin make 
![Screenshot from 2022-06-30 19-01-24](https://user-images.githubusercontent.com/55374072/176650444-785d8ae5-847a-4ff2-8c18-4d53005bbe09.png)

but different problem 
No trajectory found ..

**Comment by sudarshan-s-harithas** [comment]
Hi,

Sorry for the delayed response, somehow missed this message. 

![image (3)](https://user-images.githubusercontent.com/48291759/201870972-14db9b51-d407-4eef-9f09-417f922720f2.png)

Does the map look as shown in the figure. In that case can you try reinstall octomap and ensure the EDT is working. 
Additionally, you can try  `roslaunch CCO_VOXEL MappingDrone.launch` this should help. 

Ensure that the "path_to_weights" parameter within CCO_VOXEL_Planner.launch points to the ../weight.csv file. 

Thank You
